# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/advan/T812/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    dpm \
    gz \
    lk \
    mcupm \
    md1img \
    pi_img \
    scp \
    spmfw \
    sspm \
    tee
